# server:
#   port: 8087

# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/doctor_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#     username: root
#     password: password
#     driver-class-name: com.mysql.cj.jdbc.Driver

# cloud:
#   aws:
#     credentials:
#       access-key: AKIAYSEBCZGUIXHU7XLM
#       secret-key: 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
#     region:
#       static: ap-south-1
# aws:
#   s3:
#     bucket: doctor-service1209      

# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true    
    
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

#   data:
#     redis:
#       host: localhost
#       port: 6379

#   kafka:
#     bootstrap-servers: localhost:9092

# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/

server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doctor_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: doctore-service-group

cloud:
  aws:
    credentials:
      access-key: AKIAYSEBCZGUIXHU7XLM
      secret-key: 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
    region:
      static: ap-south-1

aws:
  s3:
    bucket: doctor-service1209

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
