server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentdb
    username: raja
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

message: Student Service Running
